"use client";

import { ChangeEvent, useEffect, useMemo, useState } from "react";

type CostRecord = { project: string; charged: string; production: string; freight: string; instagram: string; notes: string; receipt?: string; receiptName?: string };
const empty: CostRecord = { project: "", charged: "", production: "", freight: "", instagram: "", notes: "" };

export default function InternalCosts() {
  const [record, setRecord] = useState<CostRecord>(empty);
  const [saved, setSaved] = useState(false);
  useEffect(() => { const value = localStorage.getItem("dutraa_internal_costs"); if (value) setRecord(JSON.parse(value)); }, []);
  const money = (value: string) => Number(value || 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
  const result = useMemo(() => Number(record.charged || 0) - Number(record.production || 0) - Number(record.freight || 0) - Number(record.instagram || 0), [record]);
  const change = (key: keyof CostRecord, value: string) => setRecord((old) => ({ ...old, [key]: value }));
  const receipt = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => setRecord((old) => ({ ...old, receipt: String(reader.result), receiptName: file.name })); reader.readAsDataURL(file); };
  const save = () => { localStorage.setItem("dutraa_internal_costs", JSON.stringify(record)); setSaved(true); setTimeout(() => setSaved(false), 2200); };
  return <main className="internal-screen"><section className="internal-wrap"><header className="internal-header"><div><p className="eyebrow">DUTRAA DESIGNER · PRIVADO</p><h1>Controle de custos</h1><p>Informações internas do projeto</p></div><a href="/">Voltar ao painel</a></header><section className="internal-grid"><article className="internal-card internal-form"><p className="eyebrow accent-eyebrow">PROJETO</p><label>Nome do projeto<input value={record.project} onChange={(e) => change("project", e.target.value)} placeholder="Ex.: Coleção de dezembro" /></label><div className="internal-fields"><label>Preço cobrado<input type="number" step="0.01" value={record.charged} onChange={(e) => change("charged", e.target.value)} placeholder="R$ 0,00" /></label><label>Custo de produção<input type="number" step="0.01" value={record.production} onChange={(e) => change("production", e.target.value)} placeholder="R$ 0,00" /></label><label>Custo de frete<input type="number" step="0.01" value={record.freight} onChange={(e) => change("freight", e.target.value)} placeholder="R$ 0,00" /></label><label>Marketing Instagram<input type="number" step="0.01" value={record.instagram} onChange={(e) => change("instagram", e.target.value)} placeholder="R$ 0,00" /></label></div><label>Observações<textarea value={record.notes} onChange={(e) => change("notes", e.target.value)} placeholder="Anotações internas do projeto..." /></label><label className="receipt-drop">Print ou comprovante de frete<input type="file" accept="image/*,.pdf" onChange={receipt}/>{record.receiptName && <small>{record.receiptName}</small>}</label><button className="internal-save" onClick={save}>SALVAR INFORMAÇÕES</button>{saved && <p className="internal-success">Informações salvas neste dispositivo.</p>}</article><aside className="internal-card internal-summary"><p className="eyebrow accent-eyebrow">RESUMO</p><h2>{record.project || "Seu projeto"}</h2><div><span>Preço cobrado</span><strong>{money(record.charged)}</strong></div><div><span>Custos totais</span><strong>{money(String(Number(record.production || 0) + Number(record.freight || 0) + Number(record.instagram || 0)))}</strong></div><div className="internal-profit"><span>Resultado líquido</span><strong>{money(String(result))}</strong></div>{record.receipt && <img src={record.receipt} alt="Comprovante de frete" />}</aside></section></section></main>;
}
