"use client";

import { useEffect, useMemo, useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";

type Piece = { id:number; code:number; description:string; quantity:number; material?:string; weightGrams?:number|null; silverGramValue?:number|null; productionStatus:string; productionValue:number; bathStatus?:string|null; bathValue?:number|null; bathSendStatus?:string|null; bathSendValue?:number|null; bathReturnStatus?:string|null; bathReturnValue?:number|null; mailStatus?:string|null; mailValue?:number|null; transportValue?:number|null; paidValue?:number|null; photoKey?:string|null; notes?:string|null };
type Draft = Omit<Piece,"id">;
const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
const materials=["Prata maciça","Ouro 18k · 10 milésimos","Ouro 18k · 15 milésimos","Ouro 18k · 20 milésimos","Ródio","Outro"];
const cost=(p:Draft|Piece)=>Number(p.productionValue||0)+Number(p.bathValue||0)+Number(p.bathSendValue||0)+Number(p.bathReturnValue||0)+Number(p.mailValue||0)+((p.bathSendValue==null&&p.bathReturnValue==null&&p.mailValue==null)?Number((p as Piece).transportValue||0):0)+((p.material==="Prata maciça"?Number(p.weightGrams||0)*Number(p.silverGramValue||0):0));
const blank=(code:number):Draft=>({code,description:"",quantity:1,material:"Ouro 18k · 10 milésimos",weightGrams:null,silverGramValue:null,productionStatus:"EM PRODUÇÃO",productionValue:0,bathStatus:null,bathValue:null,bathSendStatus:null,bathSendValue:null,bathReturnStatus:null,bathReturnValue:null,mailStatus:null,mailValue:null,paidValue:0,photoKey:null,notes:null});

export default function Home(){
 const [pieces,setPieces]=useState<Piece[]>([]); const [draft,setDraft]=useState<Draft|null>(null); const [notice,setNotice]=useState(""); const [draggingPhoto,setDraggingPhoto]=useState(false);
 const load=async()=>{const r=await fetch("/api/pieces",{cache:"no-store"}); const d=await r.json(); if(!r.ok)throw new Error(d.error||"Falha ao carregar peças"); setPieces(d.pieces||[])};
 useEffect(()=>{void load().catch(()=>setNotice("Não foi possível carregar os registros."))},[]);
 const totals=useMemo(()=>({paid:pieces.reduce((s,p)=>s+Number(p.paidValue||0),0),open:pieces.reduce((s,p)=>s+Math.max(0,cost(p)-Number(p.paidValue||0)),0)}),[pieces]);
 const patch=async(id:number,values:Partial<Piece>)=>{const r=await fetch("/api/pieces",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,...values})}); const d=await r.json(); if(!r.ok){setNotice(d.error||"Não foi possível salvar");return;} setPieces(x=>x.map(p=>p.id===id?d.piece:p));};
 const add=async()=>{if(!draft?.description.trim())return setNotice("Digite o nome da peça na nova linha."); const r=await fetch("/api/pieces",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(draft)}); const d=await r.json(); if(!r.ok){setNotice(d.error||"Não foi possível adicionar");return;} setPieces(x=>[d.piece,...x]);setDraft(null);};
 const del=async(id:number)=>{if(!confirm("Excluir esta linha?"))return; await fetch("/api/pieces",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id})});setPieces(x=>x.filter(p=>p.id!==id));};
 const number=(value:string)=>value===""?null:Number(value);
 const upload=async(id:number,file:File)=>{if(!file.type.startsWith("image/")){setNotice("Solte uma imagem JPG, PNG, WEBP ou GIF.");return;}setNotice("");try{const body=new FormData();body.append("file",file);const r=await fetch("/api/pieces/photo",{method:"POST",body});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Falha no envio (${r.status}).`);await patch(id,{photoKey:d.key});}catch(error){setNotice(error instanceof Error?error.message:"Não foi possível enviar a foto.");}};
 const handlePhotoDrop=(id:number,e:React.DragEvent<HTMLDivElement>)=>{e.preventDefault();e.stopPropagation();setDraggingPhoto(false);const file=e.dataTransfer.files?.[0];if(file)void upload(id,file);};
 const editCell=(p:Piece,key:keyof Piece,content:React.ReactNode)=><td>{content}</td>;
 const row=(p:Piece,isDraft=false)=>{const data=isDraft?draft!:p; const change=(key:keyof Draft,v:unknown)=>isDraft?setDraft({...data,[key]:v}):void patch(p.id,{[key]:v} as Partial<Piece>); const paid=Number(data.paidValue||0), total=cost(data), open=Math.max(0,total-paid); return <tr key={isDraft?"draft":p.id} className={isDraft?"draft-row":""}>
  <td><div className={`photo-cell ${draggingPhoto?"photo-dragging":""}`} onDragEnter={e=>{e.preventDefault();e.stopPropagation();if(!isDraft)setDraggingPhoto(true)}} onDragOver={e=>{e.preventDefault();e.stopPropagation();if(!isDraft){e.dataTransfer.dropEffect="copy";setDraggingPhoto(true)}}} onDragLeave={()=>setDraggingPhoto(false)} onDrop={e=>{if(!isDraft)handlePhotoDrop(p.id,e)}}>{!isDraft&&p.photoKey?<img src={`/api/pieces/photo?key=${encodeURIComponent(p.photoKey)}`} alt="Foto da peça"/>:<label>＋<span>Solte a foto<br/>ou clique</span><input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f&&!isDraft)void upload(p.id,f)}}/></label>}</div></td>
  <td><input className="ref-input" value={data.code} type="number" onChange={e=>change("code",Number(e.target.value))}/></td>
  <td><input className="name-input" placeholder="Nome da peça" value={data.description} onChange={e=>change("description",e.target.value)}/><small>{data.quantity||1} un.</small></td>
  <td><select value={data.material||"Outro"} onChange={e=>change("material",e.target.value)}>{materials.map(m=><option key={m}>{m}</option>)}</select>{data.material==="Prata maciça"&&<input placeholder="R$/g" type="number" value={data.silverGramValue??""} onChange={e=>change("silverGramValue",number(e.target.value))}/>}</td>
  <td><select className={data.productionStatus==="FINALIZADO"?"status-selected":""} value={data.productionStatus} onChange={e=>change("productionStatus",e.target.value)}><option>EM PRODUÇÃO</option><option>FINALIZADO</option></select><input placeholder="R$ produção" type="number" value={data.productionValue||""} onChange={e=>change("productionValue",Number(e.target.value))}/></td>
  <td><input placeholder="gramas" type="number" value={data.weightGrams??""} onChange={e=>change("weightGrams",number(e.target.value))}/></td>
  <td><select className={data.bathStatus==="FINALIZADO"?"status-selected":""} value={data.bathStatus||""} onChange={e=>change("bathStatus",e.target.value||null)}><option value="">—</option><option>AGUARDANDO</option><option>EM BANHO</option><option>FINALIZADO</option></select><input placeholder="R$ banho" type="number" value={data.bathValue??""} onChange={e=>change("bathValue",number(e.target.value))}/></td>
  <td className="logistics"><label>Ida<select value={data.bathSendStatus||""} onChange={e=>change("bathSendStatus",e.target.value||null)}><option value="">—</option><option>ENVIADO</option></select><input placeholder="R$" type="number" value={data.bathSendValue??""} onChange={e=>change("bathSendValue",number(e.target.value))}/></label><label>Retorno<select value={data.bathReturnStatus||""} onChange={e=>change("bathReturnStatus",e.target.value||null)}><option value="">—</option><option>RECEBIDO</option></select><input placeholder="R$" type="number" value={data.bathReturnValue??""} onChange={e=>change("bathReturnValue",number(e.target.value))}/></label><label>Envio Correio<select value={data.mailStatus||""} onChange={e=>change("mailStatus",e.target.value||null)}><option value="">—</option><option>ENVIADO</option></select><input placeholder="R$" type="number" value={data.mailValue??""} onChange={e=>change("mailValue",number(e.target.value))}/></label></td>
  <td><strong>{money.format(total)}</strong></td><td><input placeholder="R$ pago" type="number" value={data.paidValue??""} onChange={e=>change("paidValue",number(e.target.value))}/></td><td><strong className={open?"open":"settled"}>{money.format(open)}</strong></td><td>{isDraft?<Button size="sm" onClick={add}>Salvar</Button>:<button className="delete" onClick={()=>void del(p.id)}><Trash2 size={15}/></button>}</td></tr>};
 return <main className="app-shell"><div className="app-container"><header className="topbar"><div><p className="eyebrow">DUTRAA DESIGNER</p><h1>Controle de pingentes</h1></div></header><section className="dashboard"><article><span>Já pagou</span><strong>{money.format(totals.paid)}</strong></article><article><span>Falta pagar</span><strong>{money.format(totals.open)}</strong></article></section>{notice&&<p className="notice">{notice}</p>}<section className="workspace-card"><div className="new-order"><Button onClick={()=>setDraft(blank(Math.max(0,...pieces.map(p=>p.code))+1))}><Plus size={17}/> NOVO PEDIDO</Button></div><div className="workspace-heading"><div><p className="eyebrow accent-eyebrow">ACOMPANHAMENTO</p><h2>Pedidos em produção</h2></div><span>{pieces.length} peças</span></div><div className="table-scroll"><table><thead><tr><th>FOTO</th><th>REF.</th><th>PEÇA</th><th>MATERIAL</th><th>PRODUÇÃO</th><th>PESO</th><th>BANHO</th><th>LOGÍSTICA</th><th>CUSTO TOTAL</th><th>JÁ PAGOU</th><th>EM ABERTO</th><th/></tr></thead><tbody>{draft&&row({id:0,...draft},true)}{pieces.map(p=>row(p))}</tbody></table></div></section></div></main>;
}
